# Generated by Django 5.2 on 2025-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fibra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=100)),
                (
                    "tipo_fibra",
                    models.CharField(
                        choices=[
                            ("FTTH", "Fibra até a casa"),
                            ("FTTC", "Fibra até o armário"),
                            ("FTTB", "Fibra até o prédio"),
                        ],
                        max_length=4,
                    ),
                ),
                ("nivel_sinal", models.FloatField()),
                ("data_medicao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
