# Generated by Django 5.2 on 2025-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fibra",
            name="bairro",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fibra",
            name="cep",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="fibra",
            name="cidade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fibra",
            name="estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="fibra",
            name="numero",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="fibra",
            name="rua",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
